### ISSUE TITLE
Option to only include 2 groups in the array/only send requests to the lists you're dragging between?

### ISSUE THREAD

**Issue by seabasss** [nextapps-be/livewire-sortablejs#15]
This package is amazing! I like the original one, but this took care of 3-4 glitches that I struggled with using the other package.

There's only one thing that made it trickier for my use case. I have a parent livewire component and then child livewire components each containing lists where you can drag items between the livewire components. With the original package this sent one request to the parent component. With this package it sends multiple requests to the child components.

I moved my reorder method to the child component and rewrote some parts and it's working pretty well, but the one thing I'm having difficulties with is that I only need the reorder array to contain the two lists that I'm dragging items between, and ideally only send requests to those two child components.

Right now I can do a check and see if there are two lists and if there are I know that one will be the one I moved from and the other one the one I'm moving to. With three lists or more, there is no way (that I have found) to know which lists should be updated.

Another way I can think of is if the array contained info about which one you're moving from and which one you're moving to. Just one extra parameter.

One more way would be to have an option to only send to the parent component like the original package and do all updates in one place. You’d need emits to update the children or change wire:key to make it update or something.

Any ideas of how to get around this?

Thank you so much! I'm very happy to have found this package!

**Comment by gdebrauwer** [comment]
> There's only one thing that made it trickier for my use case. I have a parent livewire component and then child livewire components each containing lists where you can drag items between the livewire components. With the original package this sent one request to the parent component. With this package it sends multiple requests to the child components.

In v0.4.0, this has been fixed. The package will now call the method on the Livewire component that has the element with the `wire:sortable-group` attribute. This is now the same behavior as the `livewire/sortable` package

**Comment by gdebrauwer** [comment]
I will close this issue for now. If you still have a problem, please open a new issue.
