### ISSUE TITLE
clash with alpine

### ISSUE THREAD

**Issue by colinmackinlay** [nextapps-be/livewire-sortablejs#16]
When I use this instead of `livewire-sortable` on the same page as AlpineJS it clashes and throws lots of errors on page load.

Has anyone else experienced this and/or found a way to overcome?

**Comment by rohan-krishna** [comment]
Same issue.

**Comment by gdebrauwer** [comment]
Are you using a cdn url for both Alpine.js and this package? Make sure that you load this package before Alpine.js is started.
When you are using Livewire, you won't have that issue anymore as Alpine.js is bundled in Livewire v3.
