### ISSUE TITLE
Drag group to become a child of another group

### ISSUE THREAD

**Issue by randohinn** [nextapps-be/livewire-sortablejs#17]
Say I have this hirearchy.

- Option A
- Option B
- Option C
  - Option D

I can freely drag option D into A and B and C inbetween A and B.  Is there any way I can allow dragging A under B (but not C under B), so basically I want to make top level items into second level ones if they don't have anything under them already.

**Comment by gdebrauwer** [comment]
I think you could achieve this by providing functions to the `pull` and `put` settings of the `group` option (see https://github.com/SortableJS/Sortable?tab=readme-ov-file#group-option). You can set this using the `wire:sortable-group.options` attribute on every group
