### ISSUE TITLE
Glitch in Safari

### ISSUE THREAD

**Issue by seabasss** [nextapps-be/livewire-sortablejs#18]
Thanks for this package!

Anyone else experiencing a glitch in Safari where you need to click on the page after you've dragged and dropped an item. Otherwise it's non-reactive. This happens after every drag and drop. It's as if Safari is still in drag state after it's dropped and doesn't get out of it until the next click.

Ideas? Thanks!

**Comment by gdebrauwer** [comment]
I can not reproduce this glitch. If you still have this issue, I think this issue is not caused by this package but by the Sortablejs package itself. Maybe try to create an issue in the https://github.com/SortableJS/Sortable repo.
