### ISSUE TITLE
Cloning and disable

### ISSUE THREAD

**Issue by nam-co** [nextapps-be/livewire-sortablejs#2]
Hi, thanks for the work on this package, why don't you send it to laravel news?

I was wondering if it's possible to implement Cloning and Disabling Sorting https://sortablejs.github.io/Sortable/#sorting-disabled

Thanks for your time

**Comment by gdebrauwer** [comment]
We currently have no plans to implement cloning and disabling sorting, as we don't need that in our current projects. But feel free to create a PR 🙂
