### ISSUE TITLE
Uncaught Livewire Sortable.js Plugin: window.Livewire is undefined. Make sure @livewireScripts is placed above this script include

### ISSUE THREAD

**Issue by martin-ro** [nextapps-be/livewire-sortablejs#27]
v3 doesn't use `@livewireScripts` anymore.

**Comment by reasecret** [comment]
Same issue...

**Comment by sfc3lf44** [comment]
Also same issue with updated version

**Comment by chillbram** [comment]
With the new way to use Livewire (that is without explicit declaration of `@livewireScripts` and `@livewireStyles` in your layout file), Livewire is actually only initialized if there are Livewire components on render. The result is that there should be no errors (with v0.3.0) on pages which contain Livewire components. The current check to see if Livewire is instantiated should, however, no longer throw an error, and probably silently stop further execution of the sortablejs script.

@gdebrauwer Could you take a look at this?

**Comment by krekas** [comment]
ping @gdebrauwer . Any plans to fix it?

**Comment by gdebrauwer** [comment]
Fixed in [v0.3.1](https://github.com/nextapps-be/livewire-sortablejs/releases/tag/0.3.1)
