### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'modifiers')

### ISSUE THREAD

**Issue by sphkress** [nextapps-be/livewire-sortablejs#28]
I use the following structure:

div wire:sortable-group="changed"
    (4x) div wire:sortable-group.item-group="..." wire:sortable-group.options="..."
        (0-n) div wire:sortable-group.item="..."

It's like 4 colums with items, similar to Trello. However, after upgrading to Livewire 3 i followed the instructions to use
    @livewireScriptConfig

and manually start Livewire in app.js

import { Livewire, Alpine } from '../../vendor/livewire/livewire/dist/livewire.esm';
import "@nextapps-be/livewire-sortablejs";
Livewire.start()

However, i get the error as described on line 51, referring to 

window.Livewire.directive('sortable-group', (el, directive, component) => {
    // Only fire this handler on the "root" group directive.
    **if (! directive.modifiers.includes('item-group')) {**
        return;
    }

**Comment by gdebrauwer** [comment]
Are you using v0.3.0 of this package? If I use v0.2.0 I get the error you describe. On v0.3.0 I do not get an error and v0.3.0 is required if you are using Livewire v3

**Comment by sphkress** [comment]
My bad. Update-behaviour is apparently different on versions below 1. I forgot to double-check, thank you!
