### ISSUE TITLE
How to get group parent

### ISSUE THREAD

**Issue by ArtMin96** [nextapps-be/livewire-sortablejs#7]
How to get the group parent after dragging into another group?

```php
[
    [
        'order' => 1,            // order of group (starts at 1, not 0)
        'value' => 20,           // group id
        'items' => [
            [
                'order' => 1,    // order of item within group (starts at 1, not 0)
                'value' => 50,   // item id
            ]
        ]
    ]
]
```

Also, groups that do not have a parent cannot become children of another group. How can I fix that? I use this part ```Multiple draggable groups with draggable items```

**Comment by gdebrauwer** [comment]
Same as https://github.com/nextapps-be/livewire-sortablejs/issues/5

Right now, I don't have any plans to add this. Feel free to create a PR to add this behavior.
