### ISSUE TITLE
Nested Sortables

### ISSUE THREAD

**Issue by pepijndik** [nextapps-be/livewire-sortablejs#8]
![image](https://user-images.githubusercontent.com/23504693/155104864-b4bdb9c4-91c2-472b-a015-e7618910a5eb.png)
Right now it is possible to swap from one group to a other group but what about,
making from a group child a new group?
i din't see any option for this is there any possible way that we can achieve this ?
Just like the example on sortablejs.

**Comment by gdebrauwer** [comment]
At the moment we have no plans to add this, but feel free to create a PR that adds this behavior.
